"""Playbook phase graphs, as generated by build/gen-routes.py.

A project's own installed copy wins, because it matches the playbooks that run actually followed.
The copy shipped inside this package is the fallback.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Optional

from ..hosts import HOSTS
from ..store import Build

REL = "poteto-mode/scripts/routes.json"


def _installed(cwd: Path) -> Optional[Path]:
    for host in HOSTS.values():
        p = cwd / host.skill_dir / REL
        if p.is_file():
            return p
    return None


def bundled() -> dict:
    for key in ("claude", "codex", "copilot", "generic"):
        b = Build.load(key)
        if b is None:
            continue
        rel = f"{HOSTS[key].skill_dir}/{REL}"
        if rel in b:
            return json.loads(b.read(rel).decode("utf-8"))
    return {}


def load(cwd: Optional[str] = None) -> dict:
    if cwd:
        p = _installed(Path(cwd))
        if p:
            try:
                return json.loads(p.read_text(encoding="utf-8"))
            except (OSError, ValueError):
                pass
    return bundled()


def script(cwd: Optional[str]) -> Optional[Path]:
    """The run-record.py a project has installed, if any."""
    if not cwd:
        return None
    for host in HOSTS.values():
        p = Path(cwd) / host.skill_dir / "poteto-mode/scripts/run-record.py"
        if p.is_file():
            return p
    return None


def bundled_script() -> Optional[bytes]:
    for key in ("claude", "codex", "copilot", "generic"):
        b = Build.load(key)
        rel = f"{HOSTS[key].skill_dir}/poteto-mode/scripts/run-record.py"
        if b is not None and rel in b:
            return b.read(rel)
    return None
